name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Se ejecuta cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Genera la animación con meses incluidos
      - name: Generate Snake SVG with months
        uses: yoshi389111/github-profile-snake@main
        id: snake
        with:
          github_user_name: paulosanchezh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00E5FF

      # Publica la animación en la rama `output`
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
